# pull official base image
FROM nginx

# Copy our customized NginX configuration (for container usage)
COPY apprise_api/nginx.conf /etc/nginx/nginx.conf
COPY apprise_api/apprise_api.conf /etc/nginx/conf.d/default.conf

# Copy our static content in place
COPY apprise_api/static /usr/share/nginx/html/s/
